ciim/routes.py
"""routes.py

main mdoule for application routes
"""

import markdown, math, operator

from io import BytesIO

from pyembed.markdown import PyEmbedMarkdown

from flask import (
    Blueprint,
    flash,
    request,
    url_for,
    redirect,
    render_template,
    abort,
    current_app,
    send_file
)
from flask_login import logout_user, current_user, login_required

from .security import AuthError, edit_user, register_user
from .database import Posts, db, Users, Courses, CoursesUsers

bp = Blueprint("ciim", __name__)


@bp.route("/inscripciones", methods=["GET", "POST"])
def inscripciones():
    if request.method == "POST":
        try:
            register_user(request.form)
        except AuthError as err:
            for error in err.errors:
                flash(f"{error}", "error")
        else:
            flash("Solicitud mandada con éxito", "success")
    return render_template("ciim/inscripciones.html")


@bp.route("/")
@bp.route("/index")
def index():
    return render_template("ciim/index.html")


@bp.route("/reglamento")
def reglamento():
    return render_template("ciim/reglamento.html")


@bp.route("/feria")
def feria():
    return render_template("ciim/feria.html")


@bp.route("/perfil", methods=("GET", "POST"))
@login_required
def perfil():
    if request.method == "POST":
        try:
            edit_user(request.form)
        except AuthError as err:
            for error in err.errors:
                flash(f"{error}", "error")
        else:
            flash("Solicitud mandada con éxito", "success")
        return redirect(url_for("ciim.perfil"))
    return render_template(
        "ciim/perfil.html", iseditable=bool(request.args.get("edit"))
    )


@bp.route("/logout")
@login_required
def logout():
    logout_user(current_user)
    return redirect(url_for("ciim.index"))


@bp.route("/editor", methods=("GET", "POST"))
@login_required
def editor():
    if request.method == "POST":
        id = 0
        if "id" in request.form:
            id = int(request.form.get("id"))
        post = Posts.query.filter_by(id=id).first()
        if id != 0 and post:
            if post.user_id == current_user.id:
                if "title" and "description" in request.form:
                    post.title = request.form.get("title")
                    post.description = request.form.get("description")
                if "content" in request.form:
                    content = request.form.get("content")
                    html = markdown.markdown(content, extensions=[PyEmbedMarkdown()])
                    db.session.commit()
                    return render_template(
                        "ciim/editor.html",
                        edit=False,
                        html=html,
                        textmarkdown=content,
                        post=post,
                    )
                elif "editcontent" in request.form:
                    content = request.form.get("editcontent")
                    db.session.commit()
                    return render_template(
                        "ciim/editor.html", edit=True, textmarkdown=content, post=post
                    )
                elif "savecontent" in request.form:
                    content = request.form.get("savecontent")
                    post.markdown = content
                    db.session.commit()
                    flash("Tu post ha sido guardado correctamente", "success")
                    return render_template(
                        "ciim/editor.html", edit=True, textmarkdown=content, post=post
                    )
                else:
                    return abort(404)
            else:
                return abort(403)
        else:
            return abort(404)
    elif "id" in request.args:
        post = Posts.query.filter_by(id=int(request.args.get("id"))).first()
        if post:
            if post.user_id == current_user.id:
                return render_template(
                    "ciim/editor.html", edit=True, post=post, textmarkdown=post.markdown
                )
            else:
                return abort(403)
        else:
            return abort(404)
    else:
        return abort(404)


@bp.route("/misproyectos/")
@bp.route("/misproyectos/<int:page>")
@login_required
def myprojects(page=1):
    posts = Posts.query.filter_by(user_id=current_user.id)
    count = posts.count()
    if count < 1:
        posts = None
    else:
        posts = posts.paginate(1, 5)
        while page != posts.page:
            if posts.has_next:
                posts = posts.next(error_out=False)
            else:
                return abort(404)
    return render_template(
        "ciim/misproyectos.html", posts=posts
    )


@bp.route("/nuevoproyecto", methods=("GET", "POST"))
@login_required
def newproject():
    if request.method == "POST":
        if "title" and "description" in request.form:
            newpost = Posts(user_id=current_user.id)
            if len(request.form.get("title")) < 64:
                newpost.title = request.form.get("title")
                newpost.description = request.form.get("description")
                db.session.add(newpost)
                db.session.commit()
                flash("Post creado correctamente, ahora deberas editarlo", "success")
                return redirect(url_for("ciim.editor", id=newpost.id))
            else:
                flash("Titulo hasta 64 caracteres", "error")
    return render_template("ciim/nuevoproyecto.html")


@bp.route("/markdoc")
@login_required
def markdoc():
    return render_template("ciim/markdoc.html")


@bp.route("/cursos")
@bp.route("/cursos/<int:page>")
def courses(page=1):
    courses = Courses.query.filter_by(is_finalized=False).order_by(Courses.creation_time.desc())
    count = courses.count()
    if count < 1:
        courses = None
    else:
        courses = courses.paginate(1, 5)
        while page != courses.page:
            if courses.has_next:
                courses = courses.next(error_out=False)
            else:
                return abort(404)
    return render_template("ciim/cursos.html", courses=courses)

@bp.route("/miscursos")
@bp.route("/miscursos/<int:page>")
@login_required
def teachcourses(page=1):
    if current_user.has_role("teacher"):
        courses = Courses.query.filter_by(user_id=current_user.id).order_by(Courses.creation_time.desc())
        count = courses.count()
        if count < 1:
            courses = None
        else:
            courses = courses.paginate(1, 5)
            while page != courses.page:
                if courses.has_next:
                    courses = courses.next(error_out=False)
                else:
                    return abort(404)
        return render_template("ciim/miscursos.html", courses=courses)
    else:
        return abort(403)

@bp.route("/image")
def image():
    """ Public images """
    if "id" and "table" in request.args:
        if request.args.get("table") == "courses":
            course = Courses.query.filter_by(id=int(request.args.get("id"))).first()
            if course:
                if course.mimetype:
                    return send_file(BytesIO(course.image), mimetype=course.mimetype, cache_timeout=-1)
                else:
                    return abort(404)
            else:
                return abort(404)
        elif request.args.get("table") == "posts":
            pass
        else:
            return abort(404)
    else:
        return abort(404)

@bp.route("/nuevocurso", methods=("GET", "POST"))
@login_required
def newcourse():
    if current_user.has_role("teacher"):
        if request.method == "POST":
            if "title" and "description" in request.form:
                newcourse = Courses(user_id=current_user.id)
                if len(request.form.get("title")) < 64:
                    newcourse.title = request.form.get("title")
                    newcourse.description = request.form.get("description")
                    if request.files['image'].filename != '':
                        newcourse.image = request.files["image"].read()
                        newcourse.mimetype = request.files["image"].mimetype
                    db.session.add(newcourse)
                    db.session.commit()
                    flash("Curso creado correctamente", "success")
                    return redirect(url_for("ciim.teachcourses"))
                else:
                    flash("Titulo hasta 64 caracteres", "error")
        return render_template("ciim/nuevocurso.html")
    else:
        return abort(403)

@bp.route("/curso/aprobar/<int:id>", methods=("GET", "POST"))
@login_required
def approve(id):
    course = Courses.query.filter_by(id=id).first()
    if current_user.id == course.user_id:
        if "toggle" in request.args:
            user_id = int(request.args.get("toggle"))
            course_user = CoursesUsers.query.filter_by(user_id=user_id).first()
            course_user.approve = not course_user.approve
            db.session.commit()
        return render_template("ciim/aprobar.html", course=course)
    else:
        return abort(403)

@bp.route("/curso/<int:id>", methods=("GET", "POST"))
def course(id):
    course = Courses.query.filter_by(id=id).first()
    teacher = Users.query.filter_by(id=course.user_id).first()
    if "join" in request.args:
        if not course.is_student(current_user):
            flash("Solicitud mandada", "success")
            course.add_student(current_user)
            db.session.commit()
        else:
            flash("¡Ya mandaste la solicitud!", "error")
    is_student = course.is_student(current_user)
    is_approved = course.is_approved(current_user)
    if "delete" in request.args and current_user.id == course.user_id:
        if bool(request.args.get("delete")):
            db.session.delete(course)
            db.session.commit()
            flash("Curso borrado", "success")
            return redirect(url_for("ciim.teachcourses"))

ciim/templates/base.html
<!DOCTYPE HTML>
<!--
    Directive by HTML5 UP
    html5up.net | @n33co
    Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="shortcut icon" type="image/png" href="{{ url_for('static', filename='images/favicon.png')}}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='assets/css/main.css')}}" />
    <!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
    <!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
    <title>{% block title %}{% endblock %}</title>
    {% block head %}{% endblock %}
</head>

<body>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <ul class=flashes>
            {% for category, message in messages %}
                <li class="{{ category }}">
                    {% if category == "error" %}
                    <div class="image icon fa-times">
                        <p>{{ message }}</p>
                    </div>
                    {% elif category == "success" %}
                    <div class="image icon fa-check-square">
                        <p>{{ message }}</p>
                    </div>
                    {% elif category == "info" %}
                    <div class="image icon fa-info">
                        <p>{{ message }}</p>
                    </div>
                    {% endif %}
                    <button onclick=event.target.parentElement.remove()>OK</button>
                </li>
            {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}

    <!-- Page Wrapper -->
    <div id="page-wrapper">

        <!-- Header -->
        <div id="header" class="alt">
            <h1> <a href="/" target="_self">CIIM</h1>
            <a href="/" target="_self" class="logo">
                <image class="icono" src="{{ url_for('static', filename='images/icono.png')}}" />
            </a>
            <nav>
                <a class="menu" href="#menu">Menú</a>
                <a href="http://blog.ciim.com.ve">Blog</a>
                {% if current_user.has_role("admin") %}
                <a href="{{ url_for('admin.index')}}">Admin</a>
                {% endif %}
                {% if not current_user.is_authenticated %}
                <a href="{{ url_for('security.login')}}">Login</a>
                {% endif %}
                {% if current_user.is_authenticated %}
                <a href="{{url_for('ciim.myprojects')}}">Proyectos</a>
                <a href="{{ url_for('ciim.perfil')}}">Perfil</a>
                <a href="{{ url_for('ciim.logout')}}">Logout</a>
                {% endif %}
            </nav>
        </div>

        <!-- Banner -->
        <section id="banner" class="alt">
            <h1>Club de Investigación e Innovación en Mecatrónica</h1>
            <a href="/" target="_self">
                <image class="icono" src="{{ url_for('static', filename='images/icono.png')}}" />
            </a>
        </section>

        <!-- Menu -->
        <nav id="menu">
            <div class="inner">
                <h2>Menú</h2>
                <ul class="links">
                    <li><a href="/">Principal</a></li>
                    {% if current_user.has_role("admin") %}
                    <li><a href="{{ url_for('admin.index')}}">Admin</a></li>
                    {% endif %}
                    {% if not current_user.is_authenticated %}
                    <li><a href="{{ url_for('security.login')}}">Login</a></li>
                    {% endif %}
                    {% if current_user.is_authenticated %}
                    <li><a href="{{url_for('ciim.myprojects')}}">Proyectos</a></li>
                    <li><a href="{{ url_for('ciim.perfil')}}">Perfil</a></li>
                    <li><a href="{{ url_for('ciim.logout')}}">Logout</a></li>
                    {% endif %}
                    <li><a href="http://blog.ciim.com.ve">Blog</a></li>
                </ul>
                <a href="#" class="close">Cerrar</a>
            </div>
        </nav>

        <!-- Main -->
        {% block main %}
        {% endblock%}

        <!-- Footer -->
        <div id="filler"></div>
        <div id="footer">
            {% block footer %}

            {% endblock %}
            <div class="container 75%">
                <!--<ul class="icons">
                            <li><a href="mailto:contacto@ciim.com.ve" class="icon fa-envelope"><span class="label">Correo Electronico</span></a></li>
                            <li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
                            <li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
                            <li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
                            <li><a href="#" class="icon fa-github"><span class="label">Github</span></a></li>
                        </ul>-->
                <ul class="copyright">
                    <li>&copy; Club CIIM. Todos los derechos reservados.</li>
                    <li>Diseño Original: <a href="http://html5up.net">HTML5 UP</a>.</li>
                    <li>Adaptado y Mantenido por <a href="mailto:wolfang.torres@gmail.com">El Administrador</a>.</li>
                </ul>
            </div>
        </div>

    </div>

    <!-- Scripts -->
    <script>
        // funcion que obtiene el valor de un query
        //TODO poner esto en una libreria aparte
        function getParameterByName(name) {
            name = name.replace(/[\[]/, "\\[").replace(/[\]]/, "\\]");
            var regex = new RegExp("[\\?&]" + name + "=([^&#]*)"),
                results = regex.exec(location.search);
            return results === null ? "" : decodeURIComponent(results[1].replace(/\+/g, " "));
        }
        // Comportamineto basico de mensajes en la pagina
        document.getElementById("mensajeFaltante").style.display = "none";
        document.getElementById("mensajeEnviado").style.display = "none";
        if (getParameterByName("estado") == "faltante") {
            document.getElementById("mensajeFaltante").style.display = "block";
        }
        else if (getParameterByName("estado") == "enviado") {
            document.getElementById("mensajeEnviado").style.display = "block";
        }
    </script>
    <script src="{{ url_for('static', filename='assets/js/skel.min.js')}}"></script>
    <script src="{{ url_for('static', filename='assets/js/jquery.min.js')}}"></script>
    <script src="{{ url_for('static', filename='assets/js/jquery.scrollex.min.js')}}"></script>
    <script src="{{ url_for('static', filename='assets/js/util.js')}}"></script>
    <!--[if lte IE 8]><script src="{{ url_for('static', filename='assets/js/ie/respond.min.js')}}"></script><![endif]-->
    <script src="{{ url_for('static', filename='assets/js/main.js')}}"></script>

</body>

</html>

ciim/templates/macros.html
{% macro render_input(field, placeholder, style) %}
  {# These automaticaly create the label and input tags, woth all the data #}
  <div>
    {% if field.errors %}
      {{ field(placeholder=placeholder, style="{} border-color: red;".format(style), **kwargs)|safe }}
    <ul>
      {% for error in field.errors %}
        <li style="text-align: center;">{{error}}</li>
      {% endfor %}
    </ul>
    {% else %}
    {{ field(placeholder=placeholder, style=style, **kwargs)|safe }}
    {% endif %}
  </div>
{% endmacro %}


{% macro render_field(field) %}
  {{ field(**kwargs)|safe }}
{% endmacro %}