ciim/routes.py
"""routes.py

main mdoule for application routes
"""

import markdown, math, operator

from io import BytesIO

from pyembed.markdown import PyEmbedMarkdown

from flask import (
    Blueprint,
    flash,
    request,
    url_for,
    redirect,
    render_template,
    abort,
    current_app,
    send_file
)
from flask_login import logout_user, current_user, login_required

from .security import AuthError, edit_user, register_user
from .database import Posts, db, Users, Courses, CoursesUsers

bp = Blueprint("ciim", __name__)


@bp.route("/inscripciones", methods=["GET", "POST"])
def inscripciones():
    if request.method == "POST":
        try:
            register_user(request.form)
        except AuthError as err:
            for error in err.errors:
                flash(f"{error}", "error")
        else:
            flash("Solicitud mandada con éxito", "success")
    return render_template("ciim/inscripciones.html")


@bp.route("/")
@bp.route("/index")
def index():
    return render_template("ciim/index.html")


@bp.route("/reglamento")
def reglamento():
    return render_template("ciim/reglamento.html")


@bp.route("/feria")
def feria():
    return render_template("ciim/feria.html")


@bp.route("/perfil", methods=("GET", "POST"))
@login_required
def perfil():
    if request.method == "POST":
        try:
            edit_user(request.form)
        except AuthError as err:
            for error in err.errors:
                flash(f"{error}", "error")
        else:
            flash("Solicitud mandada con éxito", "success")
        return redirect(url_for("ciim.perfil"))
    return render_template(
        "ciim/perfil.html", iseditable=bool(request.args.get("edit"))
    )


@bp.route("/logout")
@login_required
def logout():
    logout_user(current_user)
    return redirect(url_for("ciim.index"))


@bp.route("/editor", methods=("GET", "POST"))
@login_required
def editor():
    if request.method == "POST":
        id = 0
        if "id" in request.form:
            id = int(request.form.get("id"))
        post = Posts.query.filter_by(id=id).first()
        if id != 0 and post:
            if post.user_id == current_user.id:
                if "title" and "description" in request.form:
                    post.title = request.form.get("title")
                    post.description = request.form.get("description")
                if "content" in request.form:
                    content = request.form.get("content")
                    html = markdown.markdown(content, extensions=[PyEmbedMarkdown()])
                    db.session.commit()
                    return render_template(
                        "ciim/editor.html",
                        edit=False,
                        html=html,
                        textmarkdown=content,
                        post=post,
                    )
                elif "editcontent" in request.form:
                    content = request.form.get("editcontent")
                    db.session.commit()
                    return render_template(
                        "ciim/editor.html", edit=True, textmarkdown=content, post=post
                    )
                elif "savecontent" in request.form:
                    content = request.form.get("savecontent")
                    post.markdown = content
                    db.session.commit()
                    flash("Tu post ha sido guardado correctamente", "success")
                    return render_template(
                        "ciim/editor.html", edit=True, textmarkdown=content, post=post
                    )
                else:
                    return abort(404)
            else:
                return abort(403)
        else:
            return abort(404)
    elif "id" in request.args:
        post = Posts.query.filter_by(id=int(request.args.get("id"))).first()
        if post:
            if post.user_id == current_user.id:
                return render_template(
                    "ciim/editor.html", edit=True, post=post, textmarkdown=post.markdown
                )
            else:
                return abort(403)
        else:
            return abort(404)
    else:
        return abort(404)


@bp.route("/misproyectos/")
@bp.route("/misproyectos/<int:page>")
@login_required
def myprojects(page=1):
    posts = Posts.query.filter_by(user_id=current_user.id)
    count = posts.count()
    if count < 1:
        posts = None
    else:
        posts = posts.paginate(1, 5)
        while page != posts.page:
            if posts.has_next:
                posts = posts.next(error_out=False)
            else:
                return abort(404)
    return render_template(
        "ciim/misproyectos.html", posts=posts
    )


@bp.route("/nuevoproyecto", methods=("GET", "POST"))
@login_required
def newproject():
    if request.method == "POST":
        if "title" and "description" in request.form:
            newpost = Posts(user_id=current_user.id)
            if len(request.form.get("title")) < 64:
                newpost.title = request.form.get("title")
                newpost.description = request.form.get("description")
                db.session.add(newpost)
                db.session.commit()
                flash("Post creado correctamente, ahora deberas editarlo", "success")
                return redirect(url_for("ciim.editor", id=newpost.id))
            else:
                flash("Titulo hasta 64 caracteres", "error")
    return render_template("ciim/nuevoproyecto.html")


@bp.route("/markdoc")
@login_required
def markdoc():
    return render_template("ciim/markdoc.html")


@bp.route("/cursos")
@bp.route("/cursos/<int:page>")
def courses(page=1):
    courses = Courses.query.filter_by(is_finalized=False).order_by(Courses.creation_time.desc())
    count = courses.count()
    if count < 1:
        courses = None
    else:
        courses = courses.paginate(1, 5)
        while page != courses.page:
            if courses.has_next:
                courses = courses.next(error_out=False)
            else:
                return abort(404)
    return render_template("ciim/cursos.html", courses=courses)

@bp.route("/miscursos")
@bp.route("/miscursos/<int:page>")
@login_required
def teachcourses(page=1):
    if current_user.has_role("teacher"):
        courses = Courses.query.filter_by(user_id=current_user.id).order_by(Courses.creation_time.desc())
        count = courses.count()
        if count < 1:
            courses = None
        else:
            courses = courses.paginate(1, 5)
            while page != courses.page:
                if courses.has_next:
                    courses = courses.next(error_out=False)
                else:
                    return abort(404)
        return render_template("ciim/miscursos.html", courses=courses)
    else:
        return abort(403)

@bp.route("/image")
def image():
    """ Public images """
    if "id" and "table" in request.args:
        if request.args.get("table") == "courses":
            course = Courses.query.filter_by(id=int(request.args.get("id"))).first()
            if course:
                if course.mimetype:
                    return send_file(BytesIO(course.image), mimetype=course.mimetype, cache_timeout=-1)
                else:
                    return abort(404)
            else:
                return abort(404)
        elif request.args.get("table") == "posts":
            pass
        else:
            return abort(404)
    else:
        return abort(404)

@bp.route("/nuevocurso", methods=("GET", "POST"))
@login_required
def newcourse():
    if current_user.has_role("teacher"):
        if request.method == "POST":
            if "title" and "description" in request.form:
                newcourse = Courses(user_id=current_user.id)
                if len(request.form.get("title")) < 64:
                    newcourse.title = request.form.get("title")
                    newcourse.description = request.form.get("description")
                    if request.files['image'].filename != '':
                        newcourse.image = request.files["image"].read()
                        newcourse.mimetype = request.files["image"].mimetype
                    db.session.add(newcourse)
                    db.session.commit()
                    flash("Curso creado correctamente", "success")
                    return redirect(url_for("ciim.teachcourses"))
                else:
                    flash("Titulo hasta 64 caracteres", "error")
        return render_template("ciim/nuevocurso.html")
    else:
        return abort(403)

@bp.route("/curso/aprobar/<int:id>", methods=("GET", "POST"))
@login_required
def approve(id):
    course = Courses.query.filter_by(id=id).first()
    if current_user.id == course.user_id:
        if "toggle" in request.args:
            user_id = int(request.args.get("toggle"))
            course_user = CoursesUsers.query.filter_by(user_id=user_id).first()
            course_user.approve = not course_user.approve
            db.session.commit()
        return render_template("ciim/aprobar.html", course=course)
    else:
        return abort(403)

@bp.route("/curso/<int:id>", methods=("GET", "POST"))
def course(id):
    course = Courses.query.filter_by(id=id).first()
    teacher = Users.query.filter_by(id=course.user_id).first()
    if "join" in request.args:
        if not course.is_student(current_user):
            flash("Solicitud mandada", "success")
            course.add_student(current_user)
            db.session.commit()
        else:
            flash("¡Ya mandaste la solicitud!", "error")
    is_student = course.is_student(current_user)
    is_approved = course.is_approved(current_user)
    if "delete" in request.args and current_user.id == course.user_id:
        if bool(request.args.get("delete")):
            db.session.delete(course)
            db.session.commit()
            flash("Curso borrado", "success")
            return redirect(url_for("ciim.teachcourses"))

ciim/templates/ciim/aprobar.html
{% extends 'base.html' %}

{% block title %}
Aprobar estudiantes
{% endblock %}

{% block main %}
        <table>
            <tr>
                <th>Nombres</th>
                <th>Email</th>
                <th>Telefono</th>
                <th>Estado</th>
            </tr>
            {% for user in course.members %}
            <tr>
                <td>{{user.name}}</td>
                <td>{{user.email}}</td>
                <td>{{user.cellphone}}</td>
                <td> {% if user.approve %}
                        <a href="{{url_for('ciim.approve',id=course.id,toggle=user.id)}}"><i style="cursor: pointer; color:blue" class="fa fa-toggle-on" aria-hidden="true"></i></a>
                    {% else %}
                        <a href="{{url_for('ciim.approve',id=course.id,toggle=user.id)}}"><i style="cursor: pointer;" class="fa fa-toggle-off" aria-hidden="true"></i></a>
                    {% endif %}</td>
            </tr>
            {% endfor %}
        </table>
{% endblock %}

ciim/templates/ciim/curso.html
{% extends 'base.html' %}

{% block title %}
{{course.title}}
{% endblock %}

{% block main %}
    {% if current_user.id == teacher.id %}
        <h1>Administración de tu Curso</h1>
        {% if course.is_finalized %}
        <p style="margin-left: 2em; color:orange"><i class="icon fa-info-circle" ></i> Este curso está terminado.</p>
        {% else %}
        <p style="margin-left: 2em; color:greenyellow"><i class="icon fa-check-circle-o" ></i> Este curso está activo.</p>
        {% endif %}
        <center><a href="{{url_for('ciim.approve',id=course.id)}}">Aprobar nuevos estudiantes</a></center>
        <form method="POST" enctype="multipart/form-data" action="{{url_for('ciim.course',id=course.id)}}">
        <div style="margin-left: 3em; display:inline-block;" class="box container 75%">
            <section class="feature minor center">
                 <a class="image icon fa-pencil-square">
                     {% if course.mimetype %}
                     <img id="preview" style="width: 100%; height: 100%;" src="{{url_for('ciim.image',table='courses',id=course.id)}}" alt="Edita la imagen del curso">
                     {% else %}
                        <img id="preview" style="width: 100%; height: 100%;" src="{{ url_for('static', filename='images/pic03.jpg')}}" alt="Edita la imagen del curso">
                     {% endif %}
                     <input id="image" name="image" type="file" accept=".jpg, .jpeg, .png" style="opacity: 0; width: 100%; height: 100%; position: absolute; z-index: 100; cursor: pointer; left: 0%;"/>
                 </img>
                </a>
                <div style="position:absolute;" class="content">
                    <input type="text" name="title" id="title" style="display:none;"/>
                    <input type="text" name="description" id="description" style="display:none;"/>
                    <h1 id="edit_title" contenteditable="true">{{course.title}}</h1>
                    <p id="edit_description" contenteditable="true">{{course.description}}</p>
                </div>
             </section>
         </div>
        <ul style="display:inline-block;">
            <li><input style="margin-top: -1em; margin-bottom:1em;" type="submit" value="Clases" /></li>
            {% if course.is_finalized %}
                <li><input style="margin-top: -1em; margin-bottom:1em;" name="start" type="submit" value="Reanudar Curso" /></li>
            {% else %}
                <li><input style="margin-top: -1em; margin-bottom:1em;" name="finish" type="submit" value="Terminar Curso" /></li>
            {% endif %}
        </ul>
         <div id="save" style="display:none;" class="row">
            <div class="12u 12u(mobilep)">
                <ul class="actions">
                    <li><input type="submit" value="Guardar Cambios" /></li>
                </ul>
            </div>
        </div>
        <div class="row">
            <center style="float:initial">
                <a style="color:red; cursor:pointer; " href="{{url_for('ciim.course',id=course.id,delete=True)}}">
                    Eliminar Curso
                </a>
            </center>
        </div>
        </form>

        <script>
            window.addEventListener("load", event => {
                document.getElementById("image").onchange = event => {
                    if (event.target.files[0].size < (1024*1024)){
                        var reader  = new FileReader();
                        var preview = document.getElementById("preview");
                        reader.onloadend = function () {
                            preview.src = reader.result;
                        }
                        reader.readAsDataURL(event.target.files[0]);
                    }
                    else{
                        event.target.files[0] = null;
                        alert("max file size 1 MB !");
                    }
                    document.getElementById("save").style.display = "initial";
                }
                document.getElementById("edit_title").oninput = event => {
                    document.getElementById("title").value = document.getElementById("edit_title").innerText
                    document.getElementById("save").style.display = "initial";
                }
                document.getElementById("edit_description").oninput = event => {
                    document.getElementById("description").value = document.getElementById("edit_description").innerText
                    document.getElementById("save").style.display = "initial";
                }
            })
        </script>
    {% else %}
        <div class="box container 80%">
                    {% if course.is_finalized %}
                    <p style="color:orange"><i class="icon fa-info-circle" ></i> Este curso está terminado.</p>
                    {% else %}
                    <p style="color:greenyellow"><i class="icon fa-check-circle-o" ></i> Este curso está activo.</p>
                    {% endif %}
                    <header>
                        <h1 style="font-size: 200%;">{{course.title}}</h1>
                        <p>{{course.description}}</p>
                    </header>
                    {% if course.mimetype %}
                    <img id="preview" style="width:100%;" src="{{url_for('ciim.image',table='courses',id=course.id)}}"/>
                    {% else %}
                    <img id="preview" style="width:100%;" src="{{ url_for('static', filename='images/pic03.jpg')}}"/>
                    {% endif %}
                    {% if current_user.is_authenticated %}
                        {% if is_student %}
                            {% if is_approved %}
                                <p style="color:greenyellow"><i class="icon fa-check-circle-o" ></i> Estás aprobado.</p>
                            {% else %}
                                <p style="color:orange"><i class="icon fa-info-circle" ></i> Todavía no has sido aprobado por el profesor.</p>
                            {% endif %}
                        {% else %}
                            <center><a href="{{url_for('ciim.course',id=course.id,join=True)}}"><b>¡Inscríbete!</b></a></center>
                        {% endif %}
                    {% else %}
                    <p>¿Te interesa? Quizás debas <a href="{{url_for('ciim.inscripciones')}}">inscribirte al club</a>
                     o <a href="{{url_for('security.login')}}">ingresa</a> si ya eres miembro</p>
                    {% endif %}
        </div>
    {% endif %}
{% endblock %}

ciim/templates/ciim/cursos.html
{% extends 'base.html' %}

{% block title %}
Cursos
{% endblock %}

{% block head %}
{% endblock %}

{% block main %}
    {%  if courses %}
        <h1>Cursos</h1>
        {% for course in courses.items %}
        <div class="box container 90%">
            <section class="feature left">
                {% if course.mimetype %}
                <a href="{{url_for('ciim.course',id=course.id)}}" class="image icon fa-book">
                    <img style="width: 100%; height: 100%;" src="{{url_for('ciim.image',table='courses',id=course.id)}}"/></a>
                {% elif loop.index is divisibleby(2) %}
                <a href="{{url_for('ciim.course',id=course.id)}}" class="image icon fa-book"><img style="left: -100%;" src="{{ url_for('static', filename='images/pic05.png')}}"/></a>
                {% else %}
                <a href="{{url_for('ciim.course',id=course.id)}}" class="image icon fa-book"><img style="left: -200%;" src="{{ url_for('static', filename='images/pic05.png')}}"/></a>
                {% endif %}
                <div class="content">
                    <h3>{{course.title}}</h3>
                    <p>{{course.description}}</p>
                </div>
            </section>
        </div>
        {% endfor %}
        {% if courses.pages > 1 %}
        <div class="row" style="text-align: center;">
        <nav aria-label="Page navigation example" style="float:initial; font-size: 1.5em;">
            <ul class="pagination">
            {% if courses.has_prev %}
            <li class="page-item" style ="display: inline-block">
                <a  class="page-link" href="{{url_for('ciim.teachcourses',page=courses.page-1)}}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Anterior</span>
                </a>
            </li>
            {% endif %}
            {% if courses.has_prev %}
            <li style ="display: inline-block" class="page-item"><a class="page-link" href="{{url_for('ciim.teachcourses',page=courses.page-1)}}">{{courses.page-1}}</a></li>
            {% endif %}
            <li style ="display: inline-block" class="page-item"><a style="color: blue;" href="{{url_for('ciim.teachcourses',page=courses.page)}}" class="page-link" href="#">{{courses.page}}</a></li>
            {% if courses.has_next %}
            <li style ="display: inline-block" class="page-item"><a href="{{url_for('ciim.teachcourses',page=courses.page+1)}}" class="page-link" href="#">{{courses.page+1}}</a></li>
            {% endif %}
            {% if courses.has_next %}
            <li  style ="display: inline-block"class="page-item">
                <a class="page-link" href="{{url_for('ciim.teachcourses',page=courses.page+1)}}" aria-label="Next">
                <span class="sr-only">Siguiente</span>
                <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            {% endif %}
            </ul>
        </nav>
    </div>
    <div class="row">
        <div class="12u 12u(mobilep)">
            <ul class="actions">
                <li><a href="{{url_for('ciim.newcourse')}}"><input type="submit" value="Abrir un nuevo curso" /></a></li>
            </ul>
        </div>
    </div>
{% endif %}
    {% else %}
        <div class="row">
            <div class="12u 12u(mobilep)" style="text-align: center;">
                ¡Vaya! No hay cursos activos :(
            </div>
        </div>
    {%  endif %}
{% endblock %}

ciim/templates/ciim/index.html
{% extends 'base.html' %}

{% block title %}
Club CIIM
{% endblock %}

{% block main %}

<div id="main">

    <header class="major container 75%">
        <h2>
            Club de Investigación e Innovación en Mecatrónica
            <br />
            <br />
            Una organización de estudiantes
            <br />
            interesados en aprender y crear
        </h2>
    </header>

    <div class="box container">
        <section class="feature left">
            <a href="http://blog.ciim.com.ve" class="image icon fa-newspaper-o"><img src="{{ url_for('static', filename='images/pic01.jpg')}}" alt="Noticiero CIIM" /></a>
            <!--comienzo blog-->
            <div class="content">
                <h3>Blog</h3>
                <p>Enterate antes que todos acerca de todas las noticias importantes (Y las no tan importantes)
                    en nuestro blog.</p>
            </div>
        </section>

        <section class="feature right">
            <a href="{{url_for('ciim.inscripciones')}}" class="image icon fa-wrench"><img src="{{ url_for('static', filename='images/pic03.jpg')}}" alt="Crea, Comparte, Aprende, Repite." /></a>
            <div class="content">
                <h3>Inscripciones</h3>
                <p>¿Interesado en unirte? Las inscripciones están abiertas para todos los estudiantes de la URU.</p>
            </div>
        </section>
        <section class="feature left">
           
            <a href="{{url_for('ciim.posts')}}" class="image icon fa-cubes"><img src="{{ url_for('static', filename='images/pic02.jpg')}}" alt="Proyectos CIIM" /></a>
            <div class="content">
                <h3 style="color:rgba(255,0,0,0.8);">¡Nuevo!</h3> <h3>Proyectos</h3>
                <p>¿Quieres ver las últimas novedades de proyectos de los miembros del CIIM? Este es el apartado.</p>
            </div>
        </section>
        <section class="feature right">
            <a href="{{url_for('ciim.courses')}}" class="image icon fa-university"><img src="{{ url_for('static', filename='images/pic04.png')}}" alt="Cursos CIIM" /></a>
            <!--comienzo blog-->
            <div class="content">
                <h3 style="color:rgba(255,0,0,0.8);">¡Nuevo!</h3> <h3>Cursos</h3>
                <p>Enterate de los cursos que estamos dictando en este momento, quizás te interese alguno.</p>
            </div>
        </section>
    </div>

    <header class="major container 75%">
        <h2>Información Importante</h2>
    </header>

    <div class="box container 75%">
        <section class="feature minor left">
            <a href="{{url_for('ciim.reglamento')}}" class="image icon fa-legal"><img src="{{ url_for('static', filename='images/pic01.jpg')}}" alt="Da Rules" /></a>
            <div class="content">
                <h3>Las Reglas</h3>
            </div>
        </section>
    </div>

    {% if current_user.has_role("teacher") %}
        <div class="box container 75%">
            <section class="feature minor right">
                <a href="{{url_for('ciim.teachcourses')}}" class="image icon fa-book"><img src="{{ url_for('static', filename='images/pic04.png')}}" alt="Tus Cursos" /></a>
                <div class="content">
                    <h3>Tus Cursos</h3>
                </div>
            </section>
        </div>
    {% endif %}

</div>
        
{% endblock %}

{% block footer %}
<header class="major container 75%" id="mensajeFaltante">
    <h2>
        Disculpa,
        <br />
        Pero necesitamos que nos des tu Correo
        <br />
        para poder responderte.
    </h2>
</header>
<header class="major container 75%" id="mensajeEnviado">
    <h2>
        Gracias por tu mensaje!
        <br />
        Te responderemos tan pronto como un humano lo lea.
    </h2>
</header>

    <header class="major last">
        <h2>Contáctanos</h2>
    </header>
    <p>Expresa cualquier duda, sugerencia o comentario.</p>
    <form name="formaSugerencia" action="https://formspree.io/wolfang.torres@gmail.com" method="POST">
        <!-- <input type="hidden" name="recipient" value="wolfang.torres@gmail.com" /> -->
        <input type="hidden" name="_subject" value="Mensaje de sugerencia desde la pagina principal" />
        <!-- <input type="hidden" name="required" value="email,message" /> -->
        <input type="hidden" name="_next" value="http://ciim.com.ve/index.html?estado=enviado#mensajeEnviado" />
        <!-- <input type="hidden" name="missing_fields_redirect" value="../index.html?estado=faltante#mensajeFaltante" /> -->
        <div class="row">
            <div class="6u 12u(mobilep)">
                <input type="text" name="realname" placeholder="Nombre" />
            </div>
            <div class="6u 12u(mobilep)">
                <input type="email" name="_replyto" placeholder="Correo Electronico" />
            </div>
        </div>
        <div class="row">
            <div class="12u">
                <textarea name="message" placeholder="Mensaje" rows="6"></textarea>
            </div>
        </div>
        <div class="row">
            <div class="12u">
                <ul class="actions">
                    <li><input type="submit" value="Enviar Mensaje" /></li>
                </ul>
            </div>
        </div>
    </form>
{% endblock %}

ciim/templates/ciim/miscursos.html
{% extends 'base.html' %}

{% block title %}
Mis Cursos
{% endblock %}

{% block head %}
{% endblock %}

{% block main %}
    {%  if courses %}
        <h1>Tus Cursos</h1>
        {% for course in courses.items %}
        <div class="box container 90%">
            <section class="feature left">
                {% if course.mimetype %}
                <a href="{{url_for('ciim.course',id=course.id)}}" class="image icon fa-book">
                    <img style="width: 100%; height: 100%;" src="{{url_for('ciim.image',table='courses',id=course.id)}}"/></a>
                {% elif loop.index is divisibleby(2) %}
                <a href="{{url_for('ciim.course',id=course.id)}}" class="image icon fa-book"><img style="left: -100%;" src="{{ url_for('static', filename='images/pic05.png')}}"/></a>
                {% else %}
                <a href="{{url_for('ciim.course',id=course.id)}}" class="image icon fa-book"><img style="left: -200%;" src="{{ url_for('static', filename='images/pic05.png')}}"/></a>
                {% endif %}
                <div class="content">
                    <h3>{{course.title}}</h3>
                    <p>{{course.description}}</p>
                    {% if course.is_finalized %}
                        <p style=" color:orange"><i class="icon fa-info-circle" ></i> Este curso está terminado.</p>
                    {% else %}
                        <p style=" color:greenyellow"><i class="icon fa-check-circle-o" ></i> Este curso está activo.</p>
                    {% endif %}
                </div>
            </section>
        </div>
        {% endfor %}
        {% if courses.pages > 1 %}
        <div class="row" style="text-align: center;">
        <nav aria-label="Page navigation example" style="float:initial; font-size: 1.5em;">
            <ul class="pagination">
            {% if courses.has_prev %}
            <li class="page-item" style ="display: inline-block">
                <a  class="page-link" href="{{url_for('ciim.teachcourses',page=courses.page-1)}}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Anterior</span>
                </a>
            </li>
            {% endif %}
            {% if courses.has_prev %}
            <li style ="display: inline-block" class="page-item"><a class="page-link" href="{{url_for('ciim.teachcourses',page=courses.page-1)}}">{{courses.page-1}}</a></li>
            {% endif %}
            <li style ="display: inline-block" class="page-item"><a style="color: blue;" href="{{url_for('ciim.teachcourses',page=courses.page)}}" class="page-link" href="#">{{courses.page}}</a></li>
            {% if courses.has_next %}
            <li style ="display: inline-block" class="page-item"><a href="{{url_for('ciim.teachcourses',page=courses.page+1)}}" class="page-link" href="#">{{courses.page+1}}</a></li>
            {% endif %}
            {% if courses.has_next %}
            <li  style ="display: inline-block"class="page-item">
                <a class="page-link" href="{{url_for('ciim.teachcourses',page=courses.page+1)}}" aria-label="Next">
                <span class="sr-only">Siguiente</span>
                <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            {% endif %}
            </ul>
        </nav>
    </div>
    <div class="row">
        <div class="12u 12u(mobilep)">
            <ul class="actions">
                <li><a href="{{url_for('ciim.newcourse')}}"><input type="submit" value="Abrir un nuevo curso" /></a></li>
            </ul>
        </div>
    </div>
{% endif %}
    {% else %}
        <div class="row">
            <div class="12u 12u(mobilep)" style="text-align: center;">
                No tienes ningún curso aún <a href="{{url_for('ciim.newcourse')}}" >¡Abre uno!</a>
            </div>
        </div>
    {%  endif %}
{% endblock %}

ciim/templates/ciim/nuevoproyecto.html
{% extends 'base.html' %}

{% block title %}
Nuevo Proyecto
{% endblock %}

{% block main %}
<form method="POST" action="{{url_for('ciim.newproject')}}">
    <div class="row">
        <div class="12u 12u(mobilep)"style="text-align: center;" >
            <input name="title" type="text" placeholder="Titulo del proyecto"/>
        </div>
    </div>
    <div class="row">
        <div class="12u">
            <textarea name="description" placeholder="Descripcion del proyecto"
                rows="3"></textarea>
        </div>
    </div>
    <div class="row">
        <div class="12u 12u(mobilep)">
            <ul class="actions">
                <li><input type="submit" value="Crear Proyecto" /></li>
            </ul>
        </div>
    </div>
</form>
{% endblock %}